# Generated by Django 3.0.14 on 2023-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Назва')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Саття')),
                ('date', models.DateTimeField(verbose_name='дата публікації')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
